#
# Module manifest for module 'cSQLResources'
#
# Generated by: Mike Fal
#
# Generated on: 10/28/2014
#

@{

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'a60b18fe-9a01-4153-a75d-424a81e9ac97'

# Author of this module
Author = 'Mike Fal'

# Description of the functionality provided by this module
Description = 'Desired State Configuration community resource for managing SQL Server configurations'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# HelpInfo URI of this module
# HelpInfoURI = ''

}

